version: "3.8"

services:
  db:
    image: postgres:13
    restart: on-failure
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=cohort
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - db-data:/var/lib/postgresql/data

  api:
    image: cohort-api
    build: .
    depends_on:
      - db
    restart: on-failure
    ports:
      - 8000:8000
    environment:
      - ENV=dev
      - POSTGRES_DB=cohort
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@admin.admin
      - DJANGO_SUPERUSER_PASSWORD=admin

  worker:
    image: cohort-api
    build: .
    entrypoint: ["celery", "worker", "--app=cohort_back", "--loglevel=info"]
    depends_on:
      - broker
    restart: on-failure
    environment:
      - DJANGO_SETTINGS_MODULE=cohort_back.settings.dev
      - ENV=dev
      - POSTGRES_DB=cohort
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432

  scheduler:
    image: cohort-api
    build: .
    entrypoint: ["celery", "beat", "--app=cohort_back", "--loglevel=info"]
    depends_on:
      - broker
      - worker
    restart: on-failure
    environment:
      - DJANGO_SETTINGS_MODULE=cohort_back.settings.dev
      - ENV=dev
      - POSTGRES_DB=cohort
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432

  broker:
    image: redis:6.0.12-alpine
    restart: on-failure
    ports:
      - 6379:6379

volumes:
  db-data:

networks:
  default:
    external:
      name: arkhn_network
