version: "3.8"

services:
  db:
    image: postgres:13
    restart: on-failure
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=cohort
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - db-data:/var/lib/postgresql/data

  api:
    image: cohort
    build: .
    depends_on:
      - db
    restart: on-failure
    ports:
      - 8000:8000
    environment:
      - ENV=dev
      - POSTGRES_DB=cohort
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@admin.admin
      - DJANGO_SUPERUSER_PASSWORD=admin

volumes:
  db-data:

networks:
  default:
    external:
      name: arkhn_network
