version: "3.8"

services:
  db:
    image: postgres:13.1
    environment:
      - POSTGRES_DB=cohort
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
  web:
    build: .
    environment:
      - DJANGO_DEBUG=1
    ports:
      - "8000:8000"
    depends_on:
      - db
